name: Run Tests and Push Metrics to Prometheus

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate report
      run: npm run test -- --reporter html --output cucumber-report.html

    - name: Upload test report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-report
        path: cucumber-report.html

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install BeautifulSoup and Prometheus Client
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 prometheus_client

    - name: Parse and push to Prometheus
      run: python parse_and_push_to_prometheus.py cucumber-report.html
