name: Playwright Tests + InfluxDB

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      INFLUXDB_TOKEN: n3EQDWpJAplsOEY7kq34rTbU-w8Th61daSxKjkZGLiaADmsTcqXhvtZpItRLajikKT9s1pchxcrv-0KGHlbNjA== 
      INFLUXDB_ORG:  my-org
      INFLUXDB_BUCKET:  playwright_metrics
      INFLUXDB_URL: http://localhost:8086/orgs/2b57ae60bc5045c8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Push results to InfluxDB
        run: node sendResultsToInflux.js
